Addresses:
  FTS_DP_ADDRESS: 127.0.0.1
  FTS_USER_ADDRESS: 127.0.0.1
Filesystem:
  FTS_DB_PATH: /opt/fts/FTSDataBase.db
  FTS_MAINPATH: /home/freetak/FreeTAKServer
  FTS_LOGFILE_PATH: /opt/fts/Logs
System:
  FTS_NODE_ID: fl5m8j5txlgdtfv8wi96zf8tt0howddo
